data:
  build: ./data
  volumes:
    - ../../Projects/fixeads:/var/www/fixeads
  links:
   - db:db
  container_name: px_data
php7-fpm:
  build: ./php7-fpm
  volumes_from:
    - data
  links:
    - db:db
  working_dir: /var/www/fixeads
  container_name: px_php
nginx:
  build: ./nginx
  ports:
    - 80:80
    - 443:443
  volumes_from:
    - data
  links:
    - php7-fpm
  env_file:
    - ./nginx/nginx.env
  container_name: px_nginx
db:
  image: mysql:5.7.11
  ports:
    - 3306:3306
  env_file:
    - ./db/db.env
    - ./db/dbroot.env
  container_name: px_mysql
